import { Download, Filter, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../../components/common/Button';
import { PageHeader } from '../../components/common/PageHeader';
import { SearchInput } from '../../components/common/SearchInput';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useAppDataStore } from '../../stores/useAppDataStore';

export function AttendanceRecordsPage() {
  const [search, setSearch] = useState('');
  const studentRecords = useAppDataStore((state) => state.studentAttendance);
  const teacherRecords = useAppDataStore((state) => state.teacherAttendance);
  const rows = [...studentRecords.map((item) => ({ id: item.id, name: item.studentName, type: '學生', unit: item.className, date: item.date, status: item.status, inTime: item.checkIn, outTime: item.checkOut })), ...teacherRecords.map((item) => ({ id: item.id, name: item.staffName, type: '教職員', unit: '衡學團隊', date: item.date, status: item.status, inTime: item.checkIn, outTime: item.checkOut }))].filter((item) => item.name.includes(search) || item.unit.includes(search));
  return <div className="space-y-6"><PageHeader title="出勤紀錄" description="跨模組查詢學生與教職員出勤紀錄，支援篩選與匯出。" actions={<Button variant="secondary"><Download className="size-4" />匯出結果</Button>} /><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center"><SearchInput value={search} onChange={setSearch} className="lg:max-w-sm" placeholder="搜尋姓名或班級" /><div className="flex flex-1 flex-wrap gap-2"><input type="date" defaultValue="2026-07-01" className="h-11 rounded-xl border border-slate-200 px-3 text-sm text-slate-600" /><input type="date" defaultValue="2026-07-21" className="h-11 rounded-xl border border-slate-200 px-3 text-sm text-slate-600" /><select className="h-11 rounded-xl border border-slate-200 px-3 text-sm text-slate-600"><option>全部對象</option><option>學生</option><option>教職員</option></select><Button variant="secondary"><Filter className="size-4" />套用</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr>{['姓名', '身分', '班級／單位', '日期', '到班', '離班', '狀態'].map((title) => <th key={title} className="px-5 py-3.5 text-xs font-bold uppercase tracking-wider text-slate-500">{title}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4 text-sm font-bold text-slate-900">{row.name}</td><td className="px-5 py-4 text-sm text-slate-500">{row.type}</td><td className="px-5 py-4 text-sm text-slate-500">{row.unit}</td><td className="px-5 py-4 text-sm text-slate-500">{row.date}</td><td className="px-5 py-4 text-sm text-slate-500">{row.inTime}</td><td className="px-5 py-4 text-sm text-slate-500">{row.outTime}</td><td className="px-5 py-4"><StatusBadge status={row.status} /></td></tr>)}</tbody></table></div><div className="flex items-center gap-2 border-t border-slate-100 px-5 py-4 text-xs text-slate-500"><ShieldCheck className="size-4 text-emerald-600" />共 {rows.length} 筆符合條件的出勤資料</div></section></div>;
}
