import { BookOpen, Clock3, DoorOpen, Plus, UsersRound } from 'lucide-react';
import { Button } from '../../components/common/Button';
import { PageHeader } from '../../components/common/PageHeader';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useAppDataStore } from '../../stores/useAppDataStore';

export function ClassesPage() {
  const classes = useAppDataStore((state) => state.classes);
  return <div className="space-y-6"><PageHeader title="班級管理" description="管理開課班級、教師、教室與學生名單，掌握各班招生狀況。" actions={<Button><Plus className="size-4" />新增班級</Button>} /><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-card sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 rounded-xl bg-slate-100 p-1"><button className="rounded-lg bg-white px-4 py-2 text-sm font-bold text-slate-900 shadow-sm">進行中</button><button className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-500 hover:text-slate-900">籌備中</button><button className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-500 hover:text-slate-900">已結束</button></div><select className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-600"><option>全部年級</option><option>國中</option><option>國小</option></select></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{classes.map((item) => { const fullness = Math.round(item.studentCount / item.capacity * 100); return <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl bg-slate-100 text-slate-700"><BookOpen className="size-5" /></div><StatusBadge status={item.status} /></div><h2 className="mt-5 text-lg font-bold text-slate-950">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.grade} · {item.subject} · {item.teacherName}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-1.5 text-[11px] text-slate-400"><Clock3 className="size-3.5" />上課時間</span><p className="mt-1.5 text-xs font-bold text-slate-700">{item.schedule}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-1.5 text-[11px] text-slate-400"><DoorOpen className="size-3.5" />教室</span><p className="mt-1.5 text-xs font-bold text-slate-700">{item.classroom}</p></div></div><div className="mt-5"><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-1.5 text-slate-500"><UsersRound className="size-3.5" />班級人數</span><span className="font-bold text-slate-800">{item.studentCount} / {item.capacity}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${fullness}%` }} /></div></div><div className="mt-5 flex gap-2 border-t border-slate-100 pt-4"><Button variant="secondary" size="sm" className="flex-1">學生名單</Button><Button variant="ghost" size="sm" className="flex-1">編輯班級</Button></div></article>; })}</section></div>;
}
